dist: focal
os: linux
language: ruby
before_install: gem install bundler
cache: bundler

rvm:
  - "2.5.8"
  - "2.6.6"
  - "2.7.2"
  - "3.0.0"
  - ruby-head

jobs:
  allow_failures:
    - rvm: ruby-head

script: 'bundle exec rspec'

notifications:
  email:
    recipients:
      - adam.meehan@gmail.com
    on_failure: change
    on_success: never
